"""Export discovered project inventory into reusable tool formats."""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from autoframe.scanner.models import DiscoveredEndpoint, DiscoveredProject


def export_project_inventory(
    project: DiscoveredProject,
    output_dir: str | Path,
    *,
    formats: list[str] | None = None,
    project_path: str | None = None,
) -> dict[str, Path]:
    """Export scanner output into JSON, OpenAPI, Postman, and Markdown files."""
    selected = {item.strip().lower() for item in (formats or ["json", "openapi", "postman", "markdown"]) if item.strip()}
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    written: dict[str, Path] = {}
    if "json" in selected or "inventory" in selected:
        path = output / "inventory.json"
        _write_json(path, project_to_inventory(project, project_path=project_path))
        written["json"] = path

    if "openapi" in selected:
        path = output / "openapi.json"
        _write_json(path, project_to_openapi(project))
        written["openapi"] = path

    if "postman" in selected:
        path = output / "postman_collection.json"
        _write_json(path, project_to_postman(project))
        written["postman"] = path

    if "markdown" in selected or "md" in selected:
        path = output / "summary.md"
        path.write_text(project_to_markdown(project), encoding="utf-8")
        written["markdown"] = path

    return written


def project_to_inventory(project: DiscoveredProject, *, project_path: str | None = None) -> dict[str, Any]:
    data = asdict(project)
    _redact_sensitive(data)
    if project_path:
        _relativize_source_files(data, Path(project_path))
    data["exported_at"] = datetime.now(timezone.utc).isoformat()
    data["summary"] = {
        "project_type": project.project_type,
        "endpoint_count": len(project.endpoints),
        "resource_count": len(project.resources),
        "testable_resource_count": sum(1 for resource in project.resources if resource.testable),
        "health_endpoint_count": len(project.health_endpoints),
        "coverage_percent": _coverage_percent(project),
    }
    return data


def project_to_openapi(project: DiscoveredProject) -> dict[str, Any]:
    spec: dict[str, Any] = {
        "openapi": "3.0.3",
        "info": {
            "title": "AutoFrame Discovered API",
            "version": "0.0.0-discovered",
            "description": "Source/runtime-derived API contract generated by AutoFrame.",
        },
        "servers": [{"url": project.base_url or "/"}],
        "paths": {},
    }

    for endpoint in project.endpoints:
        if endpoint.kind not in {"http", "actuator", "download", "sse", "graphql"}:
            continue
        path_item = spec["paths"].setdefault(endpoint.path, {})
        for method in endpoint.methods:
            method_lower = method.lower()
            if method_lower not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            operation = {
                "summary": f"Discovered {method.upper()} {endpoint.path}",
                "tags": endpoint.tags or [endpoint.kind],
                "responses": {
                    "200": {"description": "Successful response"},
                    "400": {"description": "Client error"},
                    "500": {"description": "Server error"},
                },
                "x-autoframe": _endpoint_extension(endpoint),
            }
            parameters = _path_parameters(endpoint)
            if parameters:
                operation["parameters"] = parameters
            if endpoint.request_schema and method_lower in {"post", "put", "patch"}:
                operation["requestBody"] = {
                    "required": False,
                    "content": {
                        "application/json": {
                            "schema": endpoint.request_schema,
                        }
                    },
                }
            path_item[method_lower] = operation

    return spec


def project_to_postman(project: DiscoveredProject) -> dict[str, Any]:
    collection = {
        "info": {
            "name": "AutoFrame Discovered API",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "variable": [
            {"key": "baseUrl", "value": project.base_url or "http://localhost:8080"},
            {"key": "token", "value": ""},
        ],
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{token}}", "type": "string"}],
        },
        "item": [],
    }

    folders: dict[str, dict] = {}
    for endpoint in project.endpoints:
        group = _endpoint_group(endpoint.path)
        folder = folders.setdefault(group, {"name": group, "item": []})
        for method in endpoint.methods:
            if method.upper() == "WS":
                continue
            item = {
                "name": f"{method.upper()} {endpoint.path}",
                "request": {
                    "method": method.upper(),
                    "header": [{"key": "Accept", "value": "application/json"}],
                    "url": {
                        "raw": "{{baseUrl}}" + endpoint.path,
                        "host": ["{{baseUrl}}"],
                        "path": [part for part in endpoint.path.strip("/").split("/") if part],
                    },
                },
            }
            if endpoint.request_schema and method.upper() in {"POST", "PUT", "PATCH"}:
                item["request"]["header"].append({"key": "Content-Type", "value": "application/json"})
                item["request"]["body"] = {
                    "mode": "raw",
                    "raw": json.dumps(_example_from_schema(endpoint.request_schema), ensure_ascii=False, indent=2),
                    "options": {"raw": {"language": "json"}},
                }
            folder["item"].append(item)

    collection["item"] = list(folders.values())
    return collection


def project_to_markdown(project: DiscoveredProject) -> str:
    lines = [
        "# AutoFrame Discovery Summary",
        "",
        f"- Project type: `{project.project_type}`",
        f"- Base URL: `{project.base_url or ''}`",
        f"- Endpoints: `{len(project.endpoints)}`",
        f"- CRUD candidates: `{len(project.resources)}`",
        f"- Lifecycle candidates: `{sum(1 for item in project.resources if item.testable)}`",
        f"- Health endpoints: `{len(project.health_endpoints)}`",
        f"- Coverage: `{_coverage_percent(project)}`",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Kind | Source | Auth |",
        "|---|---|---|---|---|",
    ]
    for endpoint in project.endpoints:
        methods = ", ".join(endpoint.methods)
        auth = "yes" if endpoint.auth_required else "no"
        lines.append(f"| `{methods}` | `{endpoint.path}` | `{endpoint.kind}` | `{endpoint.source}` | `{auth}` |")

    lines.extend(["", "## CRUD Candidates", "", "| Resource | Operations | Confidence | Testable |", "|---|---|---|---|"])
    for resource in project.resources:
        lines.append(
            f"| `{resource.name}` | `{', '.join(resource.operations)}` | `{resource.confidence}` | `{resource.testable}` |"
        )

    return "\n".join(lines) + "\n"


def _write_json(path: Path, data: dict[str, Any]):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _coverage_percent(project: DiscoveredProject) -> Any:
    return (
        project.coverage.get("coverage_percent")
        or project.coverage.get("estimated_percent")
        or "n/a"
    )


def _redact_sensitive(value: Any):
    if isinstance(value, dict):
        for key in list(value):
            lowered = key.lower()
            if any(token in lowered for token in ("password", "token", "secret", "credential")):
                if value[key]:
                    value[key] = "<redacted>"
            else:
                _redact_sensitive(value[key])
    elif isinstance(value, list):
        for item in value:
            _redact_sensitive(item)


def _relativize_source_files(value: Any, root: Path):
    if isinstance(value, dict):
        for key, item in list(value.items()):
            if key == "source_file" and isinstance(item, str):
                try:
                    value[key] = str(Path(item).resolve().relative_to(root.resolve())).replace("\\", "/")
                except Exception:
                    value[key] = Path(item).name
            else:
                _relativize_source_files(item, root)
    elif isinstance(value, list):
        for item in value:
            _relativize_source_files(item, root)


def _endpoint_extension(endpoint: DiscoveredEndpoint) -> dict[str, Any]:
    return {
        "source": endpoint.source,
        "kind": endpoint.kind,
        "verified": endpoint.verified,
        "safe_to_call": endpoint.safe_to_call,
        "status_code": endpoint.status_code,
        "consumes": endpoint.consumes,
        "produces": endpoint.produces,
    }


def _path_parameters(endpoint: DiscoveredEndpoint) -> list[dict[str, Any]]:
    params = []
    for part in endpoint.path.split("/"):
        if part.startswith("{") and part.endswith("}"):
            name = part.strip("{}")
            params.append(
                {
                    "name": name,
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string"},
                }
            )
    return params


def _endpoint_group(path: str) -> str:
    parts = [part for part in path.strip("/").split("/") if part]
    if not parts:
        return "root"
    if parts[0] == "api" and len(parts) > 1:
        return parts[1]
    return parts[0]


def _example_from_schema(schema: dict[str, Any]) -> dict[str, Any]:
    result = {}
    for name, field in schema.get("properties", {}).items():
        field_type = field.get("type", "string")
        if field_type == "integer":
            result[name] = 1
        elif field_type == "number":
            result[name] = 1.0
        elif field_type == "boolean":
            result[name] = True
        elif field_type == "array":
            result[name] = []
        elif field_type == "object":
            result[name] = {}
        elif field.get("format") == "email":
            result[name] = "user@example.com"
        else:
            result[name] = f"sample_{name}"
    return result
